# version: '3.8'

# services:
#   django:
#     image: myusername/mydjangoapp:v2
#     container_name: django_app
#     restart: always
#     env_file: .env
#     ports:
#       - "8000:8000"
#     depends_on:
#       - postgres

#   postgres:
#     image: postgres:latest
#     container_name: postgres_db
#     restart: always
#     env_file: .env
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   watchtower:
#     image: containrrr/watchtower
#     container_name: watchtower
#     restart: always
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#     command: --interval 30

# volumes:
#   postgres_data:

# Deepseek version: 'version'
# https://chat.deepseek.com/a/chat/s/d289954f-0181-4232-b73a-533229470f4a


version: '3.8'

services:
  web:
    image: ayodelefestung/mydjangoapp:v2
    restart: unless-stopped
    env_file: .env.production
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static_root
      - media_volume:/app/media
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  static_volume:
  media_volume:
  redis_data: