# Generated by Django 5.2.1 on 2025-06-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_insight_session_id_alter_insight_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='sentimentAnswer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
