# Generated by Django 5.2.1 on 2025-06-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_product_stock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='stock_quantity',
            new_name='quantity',
        ),
    ]
